import smtplib
import ssl
import os
import asyncio
from email.message import EmailMessage
from config import PRIMARY_EMAIL, SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD
from logging_config import get_logger

logger = get_logger("ALERT", "monitor.log")

BRAND = "RoieTrackers"


def safe(v):
    """Avoid None values in email body."""
    return v if v is not None else "N/A"


def build_email(viol):
    subject = f"{BRAND} – Violation Alert for Truck {safe(viol.device_id)}"

    text_body = f"""
Violation Alert – {BRAND}

Truck: {safe(viol.device_id)}
Detected At: {safe(viol.detected_at)}
Address: {safe(viol.address)}
Duration Outside Approved Zone: {safe(viol.minutes_in_unapproved)} minutes
Type: {"Offline Violation" if viol.is_offline_violation else "Location Violation"}

This message was automatically generated by the Roie Monitoring System.
"""

    html_body = f"""
<html>
<body style="font-family:Arial, sans-serif; color:#333; line-height:1.5;">
    <div style="max-width:600px; margin:auto; padding:20px; border-radius:10px;
                border:1px solid #e5e5e5; background:#fafafa;">
        
        <h2 style="color:#1a1a1a; margin-bottom:5px;">Violation Alert</h2>
        <p style="margin-top:0; color:#555;">{BRAND} Fleet Monitoring System</p>

        <hr style="border:none; border-top:1px solid #ddd; margin:20px 0;" />

        <p><strong>Truck ID:</strong> {safe(viol.device_id)}</p>
        <p><strong>Detected At:</strong> {safe(viol.detected_at)}</p>
        <p><strong>Address:</strong> {safe(viol.address)}</p>
        <p><strong>Duration Outside Approved Zone:</strong> {safe(viol.minutes_in_unapproved)} minutes</p>
        <p><strong>Violation Type:</strong> {"Offline Violation" if viol.is_offline_violation else "Location Violation"}</p>

        <div style="margin:30px 0;">
            <a href="https://monitor.roietrackers.com/resolve/{safe(viol.id)}"
                style="display:inline-block; padding:12px 20px; background:#1e88e5;
                       color:white; text-decoration:none; font-weight:bold;
                       border-radius:6px;">
                View / Resolve Violation
            </a>
        </div>

        <p style="color:#777; font-size:12px; margin-top:30px;">
            This is an automated message from the {BRAND} Monitoring System.<br>
            If you believe this alert was sent in error, please review the device status.
        </p>
    </div>
</body>
</html>
"""

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = SMTP_USER
    msg["To"] = PRIMARY_EMAIL

    msg.set_content(text_body)
    msg.add_alternative(html_body, subtype="html")

    return msg


# ============================
#  SEND EMAIL (ASYNC SAFE)
# ============================
async def send_alert(viol):
    msg = build_email(viol)

    context = ssl.create_default_context()

    def _send_blocking():
        logger.info("[SMTP] Connecting…")
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=10) as server:
            logger.info("[SMTP] Connected. Starting TLS…")
            server.starttls(context=context)

            logger.info("[SMTP] TLS active. Logging in…")
            server.login(SMTP_USER, SMTP_PASSWORD)

            logger.info("[SMTP] Logged in. Sending message…")
            server.send_message(msg)

            logger.info("[SMTP] Message sent.")

    try:
        await asyncio.to_thread(_send_blocking)
        logger.info(f"[ALERT SUCCESS] Alert email sent for violation {viol.id}")

    except Exception as e:
        logger.error(
            f"[ALERT ERROR] Failed to send alert for violation {viol.id}: {e}",
            exc_info=True,
        )
        # do NOT re-raise: prevents worker from crashing on email failure.
